# Generated by Django 5.2.17 on 2026-09-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from store.tenant; items/history inherit via order.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="tenants.tenant",
            ),
        ),
    ]
