# Generated by Django 5.2.17 on 2026-09-27 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_products_pr_is_acti_1cd666_idx_and_more"),
        ("search", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productsearchindex",
            index=models.Index(
                fields=["product"], name="search_prod_product_5d8564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquerylog",
            index=models.Index(
                fields=["created_at"], name="search_sear_created_c9a29f_idx"
            ),
        ),
    ]
