# Generated by Django 5.2.17 on 2026-09-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from store.tenant; store-less carts stay tenant-free.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carts",
                to="tenants.tenant",
            ),
        ),
    ]
