# Generated by Django 5.2.17 on 2026-09-20 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0002_product_tenant"),
        ("stores", "0002_store_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(default="#1A73E8", max_length=9)),
                ("secondary_color", models.CharField(default="#FFB300", max_length=9)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=9)),
                ("font_family", models.CharField(default="system-ui", max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="storefront/logos/"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="storefront/heroes/"
                    ),
                ),
                (
                    "button_style",
                    models.CharField(
                        choices=[
                            ("ROUNDED", "Rounded"),
                            ("SQUARE", "Square"),
                            ("PILL", "Pill"),
                        ],
                        default="ROUNDED",
                        max_length=20,
                    ),
                ),
                (
                    "effects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Visual effects, e.g. {"hero_animation": "fade", "hover_zoom": true}.',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_theme",
                        to="stores.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("HERO", "Hero banner"),
                            ("BANNER", "Banner strip"),
                            ("CATEGORY_GRID", "Category grid"),
                            ("PRODUCT_ROW", "Product row"),
                            ("IMAGE_GALLERY", "Image gallery"),
                            ("RICH_TEXT", "Rich text block"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="storefront/sections/"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Layout knobs: columns, rows, size (sm|md|lg), effects, placeholder text — validated loosely; unknown keys are preserved.",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_sections",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("CATEGORY", "Category"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="storefront/items/"
                    ),
                ),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_items",
                        to="categories.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_items",
                        to="products.product",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="storefront.storesection",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
