# Generated by Django 5.2.17 on 2026-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storefronttheme",
            name="button_style",
            field=models.CharField(
                choices=[
                    ("ROUNDED", "Rounded"),
                    ("SQUARE", "Square"),
                    ("PILL", "Pill"),
                ],
                default="SQUARE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storefronttheme",
            name="font_family",
            field=models.CharField(
                default="Inter, system-ui, sans-serif", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="storefronttheme",
            name="primary_color",
            field=models.CharField(default="#2874F0", max_length=9),
        ),
        migrations.AlterField(
            model_name="storefronttheme",
            name="secondary_color",
            field=models.CharField(default="#FB641B", max_length=9),
        ),
    ]
