# Generated by Django 5.2.17 on 2026-09-27 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_marketplace_palette"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesection",
            name="align_x",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Horizontal focal point, 0-100 (%).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storesection",
            name="align_y",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Vertical focal point, 0-100 (%).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storesection",
            name="effect",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("zoom", "Zoom on hover"),
                    ("pan", "Pan on hover"),
                    ("grayscale", "Grayscale to color"),
                ],
                default="none",
                help_text="Interactive hover effect shown on the storefront.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="storesection",
            name="transition_ms",
            field=models.PositiveIntegerField(
                default=400,
                help_text="Effect transition duration in milliseconds.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="storesection",
            name="zoom",
            field=models.FloatField(
                default=1.0,
                help_text="Scale multiplier applied over the cover crop (1.0-3.0).",
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(3.0),
                ],
            ),
        ),
    ]
