# Generated by Django 5.2.17 on 2026-09-20 04:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("returning_users", models.PositiveIntegerField(default=0)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                (
                    "gmv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "aov",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("products_viewed", models.PositiveIntegerField(default=0)),
                ("products_added_to_cart", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "refunds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="analytics_d_date_75c1be_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="FunnelAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funnel_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("step_order", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=20)),
                ("entered", models.PositiveIntegerField(default=0)),
                ("completed", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_time_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["funnel_name", "date", "step_order"],
                "unique_together": {("funnel_name", "date", "step_order")},
            },
        ),
        migrations.CreateModel(
            name="FunnelStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("PRODUCT_VIEW", "Product View"),
                            ("ADD_TO_CART", "Add to Cart"),
                            ("REMOVE_FROM_CART", "Remove from Cart"),
                            ("CHECKOUT_START", "Checkout Start"),
                            ("PAYMENT_ATTEMPT", "Payment Attempt"),
                            ("ORDER_COMPLETE", "Order Complete"),
                            ("ORDER_CANCEL", "Order Cancel"),
                            ("SEARCH", "Search"),
                            ("CATEGORY_BROWSE", "Category Browse"),
                            ("LOGIN", "Login"),
                            ("SIGNUP", "Sign Up"),
                            ("APP_OPEN", "App Open"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("name", "order")},
            },
        ),
        migrations.CreateModel(
            name="ProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("product_id", models.UUIDField()),
                ("product_name", models.CharField(max_length=255)),
                ("views", models.PositiveIntegerField(default=0)),
                ("add_to_carts", models.PositiveIntegerField(default=0)),
                ("purchases", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-revenue"],
                "unique_together": {("date", "product_id")},
            },
        ),
        migrations.CreateModel(
            name="RetentionCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cohort_date", models.DateField()),
                ("period", models.PositiveIntegerField()),
                ("users_in_cohort", models.PositiveIntegerField()),
                ("users_active", models.PositiveIntegerField()),
                (
                    "retention_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-cohort_date", "period"],
                "unique_together": {("cohort_date", "period")},
            },
        ),
        migrations.CreateModel(
            name="RevenueByChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("channel", models.CharField(max_length=50)),
                ("orders", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "channel"],
                "unique_together": {("date", "channel")},
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("PRODUCT_VIEW", "Product View"),
                            ("ADD_TO_CART", "Add to Cart"),
                            ("REMOVE_FROM_CART", "Remove from Cart"),
                            ("CHECKOUT_START", "Checkout Start"),
                            ("PAYMENT_ATTEMPT", "Payment Attempt"),
                            ("ORDER_COMPLETE", "Order Complete"),
                            ("ORDER_CANCEL", "Order Cancel"),
                            ("SEARCH", "Search"),
                            ("CATEGORY_BROWSE", "Category Browse"),
                            ("LOGIN", "Login"),
                            ("SIGNUP", "Sign Up"),
                            ("APP_OPEN", "App Open"),
                        ],
                        max_length=20,
                    ),
                ),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="analytics_u_user_id_ef650c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="analytics_u_event_t_42317c_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="analytics_u_session_e67d95_idx",
                    ),
                ],
            },
        ),
    ]
