# Generated by Django 5.2.17 on 2026-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="categories__is_acti_3ca3e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["sort_order", "name"], name="categories__sort_or_8fce29_idx"
            ),
        ),
    ]
