# Generated by Django 5.2.17 on 2026-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["is_active", "position"], name="admin_panel_is_acti_326590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["-created_at"], name="admin_panel_created_6555e7_idx"
            ),
        ),
    ]
