# Generated by Django 5.2.17 on 2026-09-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Merchant organization that owns this store.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stores",
                to="tenants.tenant",
            ),
        ),
    ]
