# Generated by Django 5.2.17 on 2026-09-26 11:15

from django.db import migrations, models


def create_platform_store_and_rename_demo(apps, schema_editor):
    """Idempotent data step: the EASYGET platform row + guarded demo rename.

    Renames only match the exact old name; slugs are untouched (auto-slug
    only runs on empty slug, so `rahuls-store` keeps resolving for Flutter).
    """
    Store = apps.get_model("stores", "Store")
    Tenant = apps.get_model("tenants", "Tenant")
    if not Store.objects.filter(is_platform=True).exists():
        Store.objects.create(
            name="EASYGET",
            slug="easyget",
            tenant=None,
            is_platform=True,
            is_active=True,
            address_line1="EASYGET Marketplace",
            city="Bengaluru",
            state="Karnataka",
            postal_code="560001",
            latitude=12.9716,
            longitude=77.5946,
        )
    # The demo store was seeded under both spellings across environments.
    demo_names = ["Rahul's Store", "Rahuls-Store"]
    Store.objects.filter(name__in=demo_names).update(name="EasyGet Demo Store")
    Tenant.objects.filter(name__in=demo_names).update(name="EasyGet Demo Store")


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_store_tenant"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_platform", True)),
                fields=("is_platform",),
                name="unique_platform_store",
            ),
        ),
        migrations.RunPython(
            create_platform_store_and_rename_demo, migrations.RunPython.noop
        ),
    ]
