# Generated by Django 5.2.17 on 2026-09-20 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PWAConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="EasyGet", max_length=100)),
                ("short_name", models.CharField(default="EasyGet", max_length=20)),
                (
                    "description",
                    models.TextField(blank=True, default="Quick Commerce Platform"),
                ),
                ("theme_color", models.CharField(default="#2563eb", max_length=7)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("display", models.CharField(default="standalone", max_length=20)),
                (
                    "orientation",
                    models.CharField(default="portrait-primary", max_length=20),
                ),
                ("scope", models.CharField(default="/", max_length=100)),
                ("start_url", models.CharField(default="/", max_length=100)),
                ("icons", models.JSONField(default=list)),
                ("screenshots", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                ("shortcuts", models.JSONField(default=list)),
                ("related_applications", models.JSONField(default=list)),
                ("prefer_related_applications", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PWA Config",
                "verbose_name_plural": "PWA Config",
            },
        ),
        migrations.CreateModel(
            name="AppUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("WEB", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("release_notes", models.TextField()),
                ("download_url", models.URLField(blank=True, default="")),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "min_supported_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DEPLOYED", "Deployed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("platform", "version")},
            },
        ),
        migrations.CreateModel(
            name="OfflineData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTS", "Products"),
                            ("CATEGORIES", "Categories"),
                            ("STORES", "Stores"),
                            ("CART", "Cart"),
                            ("ORDERS", "Orders"),
                            ("USER_PROFILE", "User Profile"),
                            ("SETTINGS", "Settings"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "data_type", "key")},
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField()),
                ("p256dh", models.CharField(max_length=100)),
                ("auth", models.CharField(max_length=50)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
