# Generated by Django 5.2.17 on 2026-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("MERCHANT", "Merchant"),
                    ("ADMIN", "Admin"),
                    ("STORE_MANAGER", "Store Manager"),
                    ("DELIVERY_AGENT", "Delivery Agent"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
